services:
    mongo_db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME='test'
            - MONGO_INITDB_ROOT_PASSWORD='test'
            - MONGO_INITDB_DATABASE='test'
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME='test'
            - ME_CONFIG_MONGODB_AUTH_PASSWORD='test'
            - ME_CONFIG_BASICAUTH_USERNAME='test'
            - ME_CONFIG_BASICAUTH_PASSWORD='test'
        depends_on:
            - mongo_db
        ports:
          - "8888:8888"