services:
    mongo_db:
        image: mongo
        container_name: mongo
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=toor
          - MONGO_INITDB_DATABASE=dbtest
        networks:
          - mongo-test-network
        ports:
          - 27017:27017
        restart: always

    mongo-express:
        image: mongo-express
        container_name: mongo_express
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongo
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
          - ME_CONFIG_MONGODB_ADMINUSERNAME=root
          - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
          - ME_CONFIG_BASICAUTH_USERNAME=user
          - ME_CONFIG_BASICAUTH_PASSWORD=user
        depends_on:
          - mongo_db
        networks:
          - mongo-test-network
        ports:
          - "8081:8081"
        volumes:
          - mongo-data:/data/db

networks:
  mongo-test-network:
    driver: bridge

volumes:
  mongo-data: